; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__957BEFAA_cpp_linker@cpp DB 01H
msvcjmc	ENDS
PUBLIC	main
PUBLIC	__JustMyCode_Default
PUBLIC	??_C@_0M@LACCCNMM@hello?5world@			; `string'
EXTRN	?log@@YAXPEBD@Z:PROC				; log
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$main DD	imagerel $LN4
	DD	imagerel $LN4+35
	DD	imagerel $unwind$main
pdata	ENDS
;	COMDAT ??_C@_0M@LACCCNMM@hello?5world@
CONST	SEGMENT
??_C@_0M@LACCCNMM@hello?5world@ DB 'hello world', 00H	; `string'
CONST	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$main DD	010401H
	DD	04204H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT main
_TEXT	SEGMENT
main	PROC						; COMDAT
; File c:\users\sarala.kumarage\desktop\c++ practise\cpp_linker\cpp_linker\cpp_linker.cpp
; Line 6
$LN4:
	sub	rsp, 40					; 00000028H
	lea	rcx, OFFSET FLAT:__957BEFAA_cpp_linker@cpp
	call	__CheckForDebuggerJustMyCode
	lea	rcx, OFFSET FLAT:??_C@_0M@LACCCNMM@hello?5world@
	call	?log@@YAXPEBD@Z				; log
	xor	eax, eax
; Line 8
	add	rsp, 40					; 00000028H
	ret	0
main	ENDP
_TEXT	ENDS
END
