; Listing generated by Microsoft (R) Optimizing Compiler Version 19.16.27034.0 

include listing.inc

INCLUDELIB MSVCRTD
INCLUDELIB OLDNAMES

msvcjmc	SEGMENT
__90ED9BEF_math@cpp DB 01H
msvcjmc	ENDS
PUBLIC	?log@@YAPEBDPEBD@Z				; log
PUBLIC	?multiply@@YAHHH@Z				; multiply
PUBLIC	__JustMyCode_Default
EXTRN	__CheckForDebuggerJustMyCode:PROC
;	COMDAT pdata
pdata	SEGMENT
$pdata$?log@@YAPEBDPEBD@Z DD imagerel $LN4
	DD	imagerel $LN4+30
	DD	imagerel $unwind$?log@@YAPEBDPEBD@Z
pdata	ENDS
;	COMDAT pdata
pdata	SEGMENT
$pdata$?multiply@@YAHHH@Z DD imagerel $LN6
	DD	imagerel $LN6+42
	DD	imagerel $unwind$?multiply@@YAHHH@Z
pdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?multiply@@YAHHH@Z DD 040a01H
	DD	06340aH
	DD	07006320aH
xdata	ENDS
;	COMDAT xdata
xdata	SEGMENT
$unwind$?log@@YAPEBDPEBD@Z DD 020601H
	DD	030023206H
xdata	ENDS
; Function compile flags: /Odt
;	COMDAT __JustMyCode_Default
_TEXT	SEGMENT
__JustMyCode_Default PROC				; COMDAT
	ret	0
__JustMyCode_Default ENDP
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?multiply@@YAHHH@Z
_TEXT	SEGMENT
a$ = 48
b$ = 56
?multiply@@YAHHH@Z PROC					; multiply, COMDAT
; File c:\users\sarala.kumarage\desktop\c++ practise\cpp_linker\cpp_linker\math.cpp
; Line 6
$LN6:
	mov	QWORD PTR [rsp+8], rbx
	push	rdi
	sub	rsp, 32					; 00000020H
	mov	edi, ecx
	mov	ebx, edx
	lea	rcx, OFFSET FLAT:__90ED9BEF_math@cpp
	call	__CheckForDebuggerJustMyCode
	imul	edi, ebx
	mov	rbx, QWORD PTR [rsp+48]
	mov	eax, edi
; Line 9
	add	rsp, 32					; 00000020H
	pop	rdi
	ret	0
?multiply@@YAHHH@Z ENDP					; multiply
_TEXT	ENDS
; Function compile flags: /Ogtpy
;	COMDAT ?log@@YAPEBDPEBD@Z
_TEXT	SEGMENT
msg$ = 48
?log@@YAPEBDPEBD@Z PROC					; log, COMDAT
; File c:\users\sarala.kumarage\desktop\c++ practise\cpp_linker\cpp_linker\math.cpp
; Line 2
$LN4:
	push	rbx
	sub	rsp, 32					; 00000020H
	mov	rbx, rcx
	lea	rcx, OFFSET FLAT:__90ED9BEF_math@cpp
	call	__CheckForDebuggerJustMyCode
	mov	rax, rbx
; Line 4
	add	rsp, 32					; 00000020H
	pop	rbx
	ret	0
?log@@YAPEBDPEBD@Z ENDP					; log
_TEXT	ENDS
END
